version: "3"

services:
  github-search:
    image: kiendang/github-search:0.1
    ports:
      - 3000:3000
    command: ["npm", "start"]
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
